// Generated by tools/build-ranges.mjs from data/terrain/ranges.json. Do not edit.
// Every range's scores up front; each profile behind its own import.
export const RANGES = [
 {
  "id": "absaroka-range",
  "name": "Absaroka Range",
  "landmark": "Carter Mountain",
  "region": "Wyoming, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.355,
   "rawness": 0.391,
   "grandeur": 0.22,
   "dominance": 0.203
  },
  "lengthKm": 43.7,
  "reliefM": 990.8
 },
 {
  "id": "alaska-range",
  "name": "Alaska Range",
  "landmark": "Denali",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.591,
   "rawness": 0.428,
   "grandeur": 1,
   "dominance": 0.571
  },
  "lengthKm": 65.5,
  "reliefM": 4557.9
 },
 {
  "id": "aleutian-range",
  "name": "Aleutian Range",
  "landmark": "Shishaldin Volcano",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.303,
   "rawness": 0.222,
   "grandeur": 0.612,
   "dominance": 0.814
  },
  "lengthKm": 69.4,
  "reliefM": 2754.6
 },
 {
  "id": "arctic-cordillera",
  "name": "Arctic Cordillera",
  "landmark": "Mount Biederbick",
  "region": "Nunavut, Canada",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.259,
   "rawness": 0.268,
   "grandeur": 0.201,
   "dominance": 0.464
  },
  "lengthKm": 67.9,
  "reliefM": 905.3
 },
 {
  "id": "beaverhead-mountains",
  "name": "Beaverhead Mountains",
  "landmark": "Tweedy Mountain",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.425,
   "rawness": 0.466,
   "grandeur": 0.227,
   "dominance": 0.325
  },
  "lengthKm": 42.1,
  "reliefM": 1021
 },
 {
  "id": "big-horn-mountains",
  "name": "Big Horn Mountains",
  "landmark": "Bush Butte",
  "region": "Wyoming, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.301,
   "rawness": 0.302,
   "grandeur": 0.385,
   "dominance": 0.288
  },
  "lengthKm": 71.4,
  "reliefM": 1731
 },
 {
  "id": "black-range",
  "name": "Black Range",
  "landmark": "Black Mountain",
  "region": "New Mexico, USA",
  "source": "discovered",
  "archetype": "defiant",
  "mood": "defiance",
  "scores": {
   "energy": 0.161,
   "rawness": 0.156,
   "grandeur": 0.15,
   "dominance": 0.73
  },
  "lengthKm": 41.7,
  "reliefM": 676.5
 },
 {
  "id": "blue-ridge",
  "name": "Blue Ridge Mountains",
  "landmark": "Shenandoah",
  "region": "Virginia, USA",
  "source": "curated",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.21,
   "rawness": 0.204,
   "grandeur": 0.195,
   "dominance": 0.284
  },
  "lengthKm": 73.3,
  "reliefM": 878
 },
 {
  "id": "book-cliffs",
  "name": "Book Cliffs",
  "landmark": "Roan Peaks",
  "region": "Utah, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.173,
   "rawness": 0.168,
   "grandeur": 0.151,
   "dominance": 0.291
  },
  "lengthKm": 41.7,
  "reliefM": 677.3
 },
 {
  "id": "boundary-ranges",
  "name": "Boundary Ranges",
  "landmark": "Chutine Peak",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.338,
   "rawness": 0.378,
   "grandeur": 0.132,
   "dominance": 0.53
  },
  "lengthKm": 41.7,
  "reliefM": 592.2
 },
 {
  "id": "california-cascades",
  "name": "California Cascades",
  "landmark": "Mount Shasta",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.354,
   "rawness": 0.26,
   "grandeur": 0.673,
   "dominance": 0.717
  },
  "lengthKm": 60.5,
  "reliefM": 3027.9
 },
 {
  "id": "canadian-rockies",
  "name": "Canadian Rockies",
  "landmark": "Lake Louise",
  "region": "Alberta, Canada",
  "source": "curated",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.473,
   "rawness": 0.504,
   "grandeur": 0.271,
   "dominance": 0.432
  },
  "lengthKm": 49.5,
  "reliefM": 1220.6
 },
 {
  "id": "carson-range",
  "name": "Carson Range",
  "landmark": "Mount Rose",
  "region": "Nevada, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.229,
   "rawness": 0.194,
   "grandeur": 0.385,
   "dominance": 0.362
  },
  "lengthKm": 42.1,
  "reliefM": 1732.7
 },
 {
  "id": "chigmit-mountains",
  "name": "Chigmit Mountains",
  "landmark": "Redoubt Volcano",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.354,
   "rawness": 0.302,
   "grandeur": 0.452,
   "dominance": 0.778
  },
  "lengthKm": 41.7,
  "reliefM": 2033.2
 },
 {
  "id": "chiricahua-mountains",
  "name": "Chiricahua Mountains",
  "landmark": "Cochise Head",
  "region": "Arizona, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.283,
   "rawness": 0.252,
   "grandeur": 0.347,
   "dominance": 0.521
  },
  "lengthKm": 63.2,
  "reliefM": 1561.5
 },
 {
  "id": "chugach-mountains",
  "name": "Chugach Mountains",
  "landmark": "Mount Marcus Baker",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.559,
   "rawness": 0.565,
   "grandeur": 0.502,
   "dominance": 0.48
  },
  "lengthKm": 44.9,
  "reliefM": 2260
 },
 {
  "id": "coast-mountains",
  "name": "Coast Mountains",
  "landmark": "Mount Priestley",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.374,
   "rawness": 0.418,
   "grandeur": 0.225,
   "dominance": 0.315
  },
  "lengthKm": 41.7,
  "reliefM": 1012.4
 },
 {
  "id": "countess-of-dufferin-range",
  "name": "Countess of Dufferin Range",
  "landmark": "Mount Patterson",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.272,
   "rawness": 0.27,
   "grandeur": 0.186,
   "dominance": 0.392
  },
  "lengthKm": 42.1,
  "reliefM": 836.2
 },
 {
  "id": "deep-creek-range",
  "name": "Deep Creek Range",
  "landmark": "Ibapah Peak",
  "region": "Utah, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.289,
   "rawness": 0.211,
   "grandeur": 0.528,
   "dominance": 0.359
  },
  "lengthKm": 65.5,
  "reliefM": 2375.2
 },
 {
  "id": "diablo-range",
  "name": "Diablo Range",
  "landmark": "Mount Oso",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.215,
   "rawness": 0.201,
   "grandeur": 0.21,
   "dominance": 0.353
  },
  "lengthKm": 41.7,
  "reliefM": 945.9
 },
 {
  "id": "fairweather-range",
  "name": "Fairweather Range",
  "landmark": "Mount Fairweather",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "wild",
  "mood": "ferocity",
  "scores": {
   "energy": 0.64,
   "rawness": 0.575,
   "grandeur": 0.889,
   "dominance": 0.446
  },
  "lengthKm": 65.5,
  "reliefM": 4002.6
 },
 {
  "id": "front-range",
  "name": "Front Range",
  "landmark": "Pikes Peak",
  "region": "Colorado, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.275,
   "rawness": 0.248,
   "grandeur": 0.346,
   "dominance": 0.723
  },
  "lengthKm": 41.7,
  "reliefM": 1554.8
 },
 {
  "id": "garibaldi-ranges",
  "name": "Garibaldi Ranges",
  "landmark": "Mount Garibaldi",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.361,
   "rawness": 0.377,
   "grandeur": 0.245,
   "dominance": 0.427
  },
  "lengthKm": 42.5,
  "reliefM": 1100.9
 },
 {
  "id": "green-mountains",
  "name": "Green Mountains",
  "landmark": "The Chin",
  "region": "Vermont, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.243,
   "rawness": 0.237,
   "grandeur": 0.219,
   "dominance": 0.47
  },
  "lengthKm": 41.7,
  "reliefM": 983.5
 },
 {
  "id": "hualapai-mountains",
  "name": "Hualapai Mountains",
  "landmark": "Hayden Peak",
  "region": "Arizona, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.21,
   "rawness": 0.17,
   "grandeur": 0.286,
   "dominance": 0.426
  },
  "lengthKm": 41.7,
  "reliefM": 1288.6
 },
 {
  "id": "jackson-mountains",
  "name": "Jackson Mountains",
  "landmark": "Parrot Peak",
  "region": "Nevada, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.226,
   "rawness": 0.198,
   "grandeur": 0.301,
   "dominance": 0.581
  },
  "lengthKm": 41.7,
  "reliefM": 1352.4
 },
 {
  "id": "klamath-mountains",
  "name": "Klamath Mountains",
  "landmark": "Page Mountain",
  "region": "Oregon, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.367,
   "rawness": 0.373,
   "grandeur": 0.274,
   "dominance": 0.374
  },
  "lengthKm": 64,
  "reliefM": 1234.3
 },
 {
  "id": "la-sal-mountains",
  "name": "La Sal Mountains",
  "landmark": "Mount Peale",
  "region": "Utah, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.257,
   "rawness": 0.205,
   "grandeur": 0.397,
   "dominance": 0.391
  },
  "lengthKm": 41.7,
  "reliefM": 1787.2
 },
 {
  "id": "laurentian-mountains",
  "name": "Laurentian Mountains",
  "landmark": "Mont Tremblant",
  "region": "Quebec, Canada",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.196,
   "rawness": 0.21,
   "grandeur": 0.09,
   "dominance": 0.507
  },
  "lengthKm": 41.7,
  "reliefM": 403.6
 },
 {
  "id": "lillooet-ranges",
  "name": "Lillooet Ranges",
  "landmark": "Cantilever Range",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.434,
   "rawness": 0.379,
   "grandeur": 0.515,
   "dominance": 0.321
  },
  "lengthKm": 67.1,
  "reliefM": 2316.3
 },
 {
  "id": "little-belt-mountains",
  "name": "Little Belt Mountains",
  "landmark": "Big Baldy Mountain",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.258,
   "rawness": 0.256,
   "grandeur": 0.24,
   "dominance": 0.408
  },
  "lengthKm": 41.7,
  "reliefM": 1082.1
 },
 {
  "id": "livingston-range",
  "name": "Livingston Range",
  "landmark": "Kintla Peak",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.489,
   "rawness": 0.518,
   "grandeur": 0.216,
   "dominance": 0.428
  },
  "lengthKm": 42.9,
  "reliefM": 973.5
 },
 {
  "id": "madison-range",
  "name": "Madison Range",
  "landmark": "Echo Peak",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.31,
   "rawness": 0.328,
   "grandeur": 0.182,
   "dominance": 0.385
  },
  "lengthKm": 42.9,
  "reliefM": 820.6
 },
 {
  "id": "mahoosuc-range",
  "name": "Mahoosuc Range",
  "landmark": "Old Speck Mountain",
  "region": "Maine, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.24,
   "rawness": 0.237,
   "grandeur": 0.19,
   "dominance": 0.455
  },
  "lengthKm": 59.3,
  "reliefM": 853.9
 },
 {
  "id": "medicine-bow-mountains",
  "name": "Medicine Bow Mountains",
  "landmark": "Medicine Bow Peak",
  "region": "Wyoming, USA",
  "source": "discovered",
  "archetype": "defiant",
  "mood": "defiance",
  "scores": {
   "energy": 0.12,
   "rawness": 0.101,
   "grandeur": 0.175,
   "dominance": 0.668
  },
  "lengthKm": 41.7,
  "reliefM": 788.7
 },
 {
  "id": "mission-mountains",
  "name": "Mission Mountains",
  "landmark": "McDonald Peak",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.363,
   "rawness": 0.367,
   "grandeur": 0.277,
   "dominance": 0.383
  },
  "lengthKm": 42.5,
  "reliefM": 1244.9
 },
 {
  "id": "monument-valley",
  "name": "Monument Valley",
  "landmark": null,
  "region": "Utah-Arizona, USA",
  "source": "curated",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.198,
   "rawness": 0.22,
   "grandeur": 0.078,
   "dominance": 0.456
  },
  "lengthKm": 19.9,
  "reliefM": 351.6
 },
 {
  "id": "north-cascades",
  "name": "North Cascades",
  "landmark": "Glacier Peak",
  "region": "Washington, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.347,
   "rawness": 0.36,
   "grandeur": 0.225,
   "dominance": 0.522
  },
  "lengthKm": 43.3,
  "reliefM": 1011.3
 },
 {
  "id": "olympic-mountains",
  "name": "Olympic Mountains",
  "landmark": "Second Top",
  "region": "Washington, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.417,
   "rawness": 0.367,
   "grandeur": 0.525,
   "dominance": 0.271
  },
  "lengthKm": 64.4,
  "reliefM": 2361.3
 },
 {
  "id": "oregon-cascades",
  "name": "Oregon Cascades",
  "landmark": "Mount Hood",
  "region": "Oregon, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.342,
   "rawness": 0.274,
   "grandeur": 0.483,
   "dominance": 0.883
  },
  "lengthKm": 41.7,
  "reliefM": 2173.5
 },
 {
  "id": "pacific-ranges",
  "name": "Pacific Ranges",
  "landmark": "Mount Raleigh",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.372,
   "rawness": 0.38,
   "grandeur": 0.258,
   "dominance": 0.528
  },
  "lengthKm": 44.5,
  "reliefM": 1160
 },
 {
  "id": "panamint-range",
  "name": "Panamint Range",
  "landmark": "Telescope Peak",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.309,
   "rawness": 0.294,
   "grandeur": 0.362,
   "dominance": 0.427
  },
  "lengthKm": 42.1,
  "reliefM": 1627.3
 },
 {
  "id": "park-ranges",
  "name": "Park Ranges",
  "landmark": "Mount Clemenceau",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.537,
   "rawness": 0.572,
   "grandeur": 0.276,
   "dominance": 0.372
  },
  "lengthKm": 42.5,
  "reliefM": 1241.3
 },
 {
  "id": "peninsular-ranges",
  "name": "Peninsular Ranges",
  "landmark": "Volcán Las Tres Vírgenes",
  "region": "Baja California Sur, Mexico",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.304,
   "rawness": 0.265,
   "grandeur": 0.428,
   "dominance": 0.562
  },
  "lengthKm": 42.1,
  "reliefM": 1927.7
 },
 {
  "id": "pinaleno-mountains",
  "name": "Pinaleño Mountains",
  "landmark": "Mount Graham",
  "region": "Arizona, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.236,
   "rawness": 0.171,
   "grandeur": 0.46,
   "dominance": 0.541
  },
  "lengthKm": 62.4,
  "reliefM": 2068.2
 },
 {
  "id": "pine-valley-mountains",
  "name": "Pine Valley Mountains",
  "landmark": "Burger Peak",
  "region": "Utah, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.282,
   "rawness": 0.217,
   "grandeur": 0.471,
   "dominance": 0.49
  },
  "lengthKm": 62.4,
  "reliefM": 2120.5
 },
 {
  "id": "rainier",
  "name": "Cascade Range",
  "landmark": "Mount Rainier",
  "region": "Washington, USA",
  "source": "curated",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.425,
   "rawness": 0.294,
   "grandeur": 0.628,
   "dominance": 0.826
  },
  "lengthKm": 31.2,
  "reliefM": 2826
 },
 {
  "id": "revelation-mountains",
  "name": "Revelation Mountains",
  "landmark": "Mount Hesperus",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.434,
   "rawness": 0.478,
   "grandeur": 0.261,
   "dominance": 0.374
  },
  "lengthKm": 42.1,
  "reliefM": 1176.2
 },
 {
  "id": "rocky-mountains",
  "name": "Rocky Mountains",
  "landmark": "Fairview Peak",
  "region": "Montana, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.352,
   "rawness": 0.302,
   "grandeur": 0.396,
   "dominance": 0.308
  },
  "lengthKm": 42.5,
  "reliefM": 1780.1
 },
 {
  "id": "saint-elias-mountains",
  "name": "Saint Elias Mountains",
  "landmark": "Mount Saint Elias",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "wild",
  "mood": "ferocity",
  "scores": {
   "energy": 0.588,
   "rawness": 0.541,
   "grandeur": 0.941,
   "dominance": 0.449
  },
  "lengthKm": 55,
  "reliefM": 4236.1
 },
 {
  "id": "san-gabriel-mountains",
  "name": "San Gabriel Mountains",
  "landmark": "Mount San Antonio",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.363,
   "rawness": 0.273,
   "grandeur": 0.589,
   "dominance": 0.299
  },
  "lengthKm": 64.7,
  "reliefM": 2652.4
 },
 {
  "id": "san-jacinto-mountains",
  "name": "San Jacinto Mountains",
  "landmark": "San Jacinto Peak",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.311,
   "rawness": 0.233,
   "grandeur": 0.546,
   "dominance": 0.604
  },
  "lengthKm": 63.2,
  "reliefM": 2458.6
 },
 {
  "id": "san-mateo-mountains",
  "name": "San Mateo Mountains",
  "landmark": "Mount Taylor",
  "region": "New Mexico, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.217,
   "rawness": 0.177,
   "grandeur": 0.329,
   "dominance": 0.517
  },
  "lengthKm": 60.1,
  "reliefM": 1482.5
 },
 {
  "id": "san-rafael-mountains",
  "name": "San Rafael Mountains",
  "landmark": "Big Pine Mountain",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "defiant",
  "mood": "defiance",
  "scores": {
   "energy": 0.23,
   "rawness": 0.251,
   "grandeur": 0.163,
   "dominance": 0.608
  },
  "lengthKm": 62,
  "reliefM": 732.7
 },
 {
  "id": "sangre-de-cristo-mountains",
  "name": "Sangre de Cristo Mountains",
  "landmark": "Cabresto Peak",
  "region": "New Mexico, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.318,
   "rawness": 0.295,
   "grandeur": 0.387,
   "dominance": 0.34
  },
  "lengthKm": 65.5,
  "reliefM": 1740.5
 },
 {
  "id": "sangre-de-cristo-range",
  "name": "Sangre de Cristo Range",
  "landmark": "Mount Adams",
  "region": "Colorado, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.407,
   "rawness": 0.369,
   "grandeur": 0.402,
   "dominance": 0.214
  },
  "lengthKm": 65.1,
  "reliefM": 1811.2
 },
 {
  "id": "sawtooth",
  "name": "Sawtooth Range",
  "landmark": "Thompson Peak",
  "region": "Idaho, USA",
  "source": "curated",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.365,
   "rawness": 0.387,
   "grandeur": 0.146,
   "dominance": 0.447
  },
  "lengthKm": 48.8,
  "reliefM": 654.8
 },
 {
  "id": "selkirk-mountains",
  "name": "Selkirk Mountains",
  "landmark": "Mount Proteus",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.553,
   "rawness": 0.606,
   "grandeur": 0.219,
   "dominance": 0.565
  },
  "lengthKm": 44.1,
  "reliefM": 983.8
 },
 {
  "id": "sierra-de-san-pedro-martir",
  "name": "Sierra de San Pedro Mártir",
  "landmark": "Picacho del Diablo",
  "region": "Baja California, Mexico",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.247,
   "rawness": 0.218,
   "grandeur": 0.29,
   "dominance": 0.362
  },
  "lengthKm": 45.2,
  "reliefM": 1306.5
 },
 {
  "id": "sierra-estrella",
  "name": "Sierra Estrella",
  "landmark": "Montezuma Peak",
  "region": "Arizona, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.217,
   "rawness": 0.198,
   "grandeur": 0.231,
   "dominance": 0.55
  },
  "lengthKm": 42.1,
  "reliefM": 1038.3
 },
 {
  "id": "sierra-madre-del-sur",
  "name": "Sierra Madre del Sur",
  "landmark": "Cerro Tiotepec",
  "region": "Guerrero, Mexico",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.334,
   "rawness": 0.291,
   "grandeur": 0.499,
   "dominance": 0.304
  },
  "lengthKm": 61.2,
  "reliefM": 2247.2
 },
 {
  "id": "sierra-madre-occidental",
  "name": "Sierra Madre Occidental",
  "landmark": "Cerro Mohinora",
  "region": "Chihuahua, Mexico",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.272,
   "rawness": 0.341,
   "grandeur": 0.23,
   "dominance": 0.646
  },
  "lengthKm": 42.5,
  "reliefM": 1034
 },
 {
  "id": "sierra-madre-oriental",
  "name": "Sierra Madre Oriental",
  "landmark": "Cerro La Viga",
  "region": "Coahuila, Mexico",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.27,
   "rawness": 0.27,
   "grandeur": 0.313,
   "dominance": 0.323
  },
  "lengthKm": 62.8,
  "reliefM": 1408.3
 },
 {
  "id": "sierra-mixteca",
  "name": "Sierra Mixteca",
  "landmark": "Cerro Zempoaltepec",
  "region": "Oaxaca, Mexico",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.277,
   "rawness": 0.264,
   "grandeur": 0.276,
   "dominance": 0.571
  },
  "lengthKm": 43.7,
  "reliefM": 1239.8
 },
 {
  "id": "sierra-whitney",
  "name": "Sierra Nevada",
  "landmark": "Mount Whitney",
  "region": "California, USA",
  "source": "curated",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.494,
   "rawness": 0.586,
   "grandeur": 0.44,
   "dominance": 0.608
  },
  "lengthKm": 65.5,
  "reliefM": 1979.7
 },
 {
  "id": "skagit-range",
  "name": "Skagit Range",
  "landmark": "Mount Baker",
  "region": "Washington, USA",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.387,
   "rawness": 0.314,
   "grandeur": 0.536,
   "dominance": 0.628
  },
  "lengthKm": 42.1,
  "reliefM": 2412
 },
 {
  "id": "skeena-mountains",
  "name": "Skeena Mountains",
  "landmark": "Delta Peak",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.331,
   "rawness": 0.348,
   "grandeur": 0.217,
   "dominance": 0.256
  },
  "lengthKm": 42.5,
  "reliefM": 976.8
 },
 {
  "id": "strawberry-range",
  "name": "Strawberry Range",
  "landmark": "Strawberry Mountain",
  "region": "Oregon, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.264,
   "rawness": 0.27,
   "grandeur": 0.363,
   "dominance": 0.324
  },
  "lengthKm": 67.9,
  "reliefM": 1635.2
 },
 {
  "id": "taconic-mountains",
  "name": "Taconic Mountains",
  "landmark": "Dorset Mountain",
  "region": "Vermont, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.234,
   "rawness": 0.244,
   "grandeur": 0.115,
   "dominance": 0.411
  },
  "lengthKm": 41.7,
  "reliefM": 516.7
 },
 {
  "id": "tetons",
  "name": "Teton Range",
  "landmark": "Grand Teton",
  "region": "Wyoming, USA",
  "source": "curated",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.424,
   "rawness": 0.445,
   "grandeur": 0.253,
   "dominance": 0.751
  },
  "lengthKm": 43.3,
  "reliefM": 1139.3
 },
 {
  "id": "thudaka-range",
  "name": "Thudaka Range",
  "landmark": "Thudaka Peak",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.425,
   "rawness": 0.482,
   "grandeur": 0.181,
   "dominance": 0.571
  },
  "lengthKm": 41.7,
  "reliefM": 814.2
 },
 {
  "id": "toquima-range",
  "name": "Toquima Range",
  "landmark": "South Summit",
  "region": "Nevada, USA",
  "source": "discovered",
  "archetype": "defiant",
  "mood": "defiance",
  "scores": {
   "energy": 0.214,
   "rawness": 0.168,
   "grandeur": 0.251,
   "dominance": 0.759
  },
  "lengthKm": 42.9,
  "reliefM": 1129.5
 },
 {
  "id": "tordrillo-mountains",
  "name": "Tordrillo Mountains",
  "landmark": "Mount Torbert",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.457,
   "rawness": 0.382,
   "grandeur": 0.649,
   "dominance": 0.225
  },
  "lengthKm": 60.5,
  "reliefM": 2920
 },
 {
  "id": "tower-of-london-range",
  "name": "Tower of London Range",
  "landmark": "King Peak",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.441,
   "rawness": 0.49,
   "grandeur": 0.126,
   "dominance": 0.557
  },
  "lengthKm": 42.1,
  "reliefM": 569
 },
 {
  "id": "trans-mexican-volcanic-belt",
  "name": "Trans-Mexican Volcanic Belt",
  "landmark": "Volcán Pico de Orizaba",
  "region": "Veracruz, Mexico",
  "source": "discovered",
  "archetype": "sublime",
  "mood": "awe",
  "scores": {
   "energy": 0.359,
   "rawness": 0.264,
   "grandeur": 0.653,
   "dominance": 0.577
  },
  "lengthKm": 42.1,
  "reliefM": 2938.8
 },
 {
  "id": "vaca-mountains",
  "name": "Vaca Mountains",
  "landmark": "Berryessa Peak",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.121,
   "rawness": 0.099,
   "grandeur": 0.192,
   "dominance": 0.24
  },
  "lengthKm": 66.3,
  "reliefM": 862.7
 },
 {
  "id": "waddington-range",
  "name": "Waddington Range",
  "landmark": "Mount Waddington",
  "region": "British Columbia, Canada",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.647,
   "rawness": 0.648,
   "grandeur": 0.452,
   "dominance": 0.676
  },
  "lengthKm": 45.6,
  "reliefM": 2033.8
 },
 {
  "id": "wallowa-mountains",
  "name": "Wallowa Mountains",
  "landmark": "Matterhorn",
  "region": "Oregon, USA",
  "source": "discovered",
  "archetype": "restless",
  "mood": "unease",
  "scores": {
   "energy": 0.336,
   "rawness": 0.376,
   "grandeur": 0.157,
   "dominance": 0.469
  },
  "lengthKm": 43.3,
  "reliefM": 706.6
 },
 {
  "id": "wasatch",
  "name": "Wasatch Range",
  "landmark": "Lone Peak",
  "region": "Utah, USA",
  "source": "curated",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.336,
   "rawness": 0.33,
   "grandeur": 0.33,
   "dominance": 0.509
  },
  "lengthKm": 60.8,
  "reliefM": 1483.6
 },
 {
  "id": "white-mountains",
  "name": "White Mountains",
  "landmark": "White Mountain Peak",
  "region": "California, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.333,
   "rawness": 0.251,
   "grandeur": 0.587,
   "dominance": 0.277
  },
  "lengthKm": 67.1,
  "reliefM": 2641.5
 },
 {
  "id": "white-pine-range",
  "name": "White Pine Range",
  "landmark": "Currant Mountain",
  "region": "Nevada, USA",
  "source": "discovered",
  "archetype": "brooding",
  "mood": "melancholy",
  "scores": {
   "energy": 0.235,
   "rawness": 0.203,
   "grandeur": 0.31,
   "dominance": 0.48
  },
  "lengthKm": 43.3,
  "reliefM": 1394.7
 },
 {
  "id": "wrangell-mountains",
  "name": "Wrangell Mountains",
  "landmark": "Mount Blackburn",
  "region": "Alaska, USA",
  "source": "discovered",
  "archetype": "majestic",
  "mood": "heroism",
  "scores": {
   "energy": 0.558,
   "rawness": 0.483,
   "grandeur": 0.857,
   "dominance": 0.515
  },
  "lengthKm": 69.8,
  "reliefM": 3857.7
 },
 {
  "id": "yukon-ranges",
  "name": "Yukon Ranges",
  "landmark": "Trapper Mountain",
  "region": "Yukon, Canada",
  "source": "discovered",
  "archetype": "serene",
  "mood": "calm",
  "scores": {
   "energy": 0.259,
   "rawness": 0.26,
   "grandeur": 0.232,
   "dominance": 0.356
  },
  "lengthKm": 41.7,
  "reliefM": 1045.7
 }
];

export const LOADERS = {
  "absaroka-range": () => import('./absaroka-range.js'),
  "alaska-range": () => import('./alaska-range.js'),
  "aleutian-range": () => import('./aleutian-range.js'),
  "arctic-cordillera": () => import('./arctic-cordillera.js'),
  "beaverhead-mountains": () => import('./beaverhead-mountains.js'),
  "big-horn-mountains": () => import('./big-horn-mountains.js'),
  "black-range": () => import('./black-range.js'),
  "blue-ridge": () => import('./blue-ridge.js'),
  "book-cliffs": () => import('./book-cliffs.js'),
  "boundary-ranges": () => import('./boundary-ranges.js'),
  "california-cascades": () => import('./california-cascades.js'),
  "canadian-rockies": () => import('./canadian-rockies.js'),
  "carson-range": () => import('./carson-range.js'),
  "chigmit-mountains": () => import('./chigmit-mountains.js'),
  "chiricahua-mountains": () => import('./chiricahua-mountains.js'),
  "chugach-mountains": () => import('./chugach-mountains.js'),
  "coast-mountains": () => import('./coast-mountains.js'),
  "countess-of-dufferin-range": () => import('./countess-of-dufferin-range.js'),
  "deep-creek-range": () => import('./deep-creek-range.js'),
  "diablo-range": () => import('./diablo-range.js'),
  "fairweather-range": () => import('./fairweather-range.js'),
  "front-range": () => import('./front-range.js'),
  "garibaldi-ranges": () => import('./garibaldi-ranges.js'),
  "green-mountains": () => import('./green-mountains.js'),
  "hualapai-mountains": () => import('./hualapai-mountains.js'),
  "jackson-mountains": () => import('./jackson-mountains.js'),
  "klamath-mountains": () => import('./klamath-mountains.js'),
  "la-sal-mountains": () => import('./la-sal-mountains.js'),
  "laurentian-mountains": () => import('./laurentian-mountains.js'),
  "lillooet-ranges": () => import('./lillooet-ranges.js'),
  "little-belt-mountains": () => import('./little-belt-mountains.js'),
  "livingston-range": () => import('./livingston-range.js'),
  "madison-range": () => import('./madison-range.js'),
  "mahoosuc-range": () => import('./mahoosuc-range.js'),
  "medicine-bow-mountains": () => import('./medicine-bow-mountains.js'),
  "mission-mountains": () => import('./mission-mountains.js'),
  "monument-valley": () => import('./monument-valley.js'),
  "north-cascades": () => import('./north-cascades.js'),
  "olympic-mountains": () => import('./olympic-mountains.js'),
  "oregon-cascades": () => import('./oregon-cascades.js'),
  "pacific-ranges": () => import('./pacific-ranges.js'),
  "panamint-range": () => import('./panamint-range.js'),
  "park-ranges": () => import('./park-ranges.js'),
  "peninsular-ranges": () => import('./peninsular-ranges.js'),
  "pinaleno-mountains": () => import('./pinaleno-mountains.js'),
  "pine-valley-mountains": () => import('./pine-valley-mountains.js'),
  "rainier": () => import('./rainier.js'),
  "revelation-mountains": () => import('./revelation-mountains.js'),
  "rocky-mountains": () => import('./rocky-mountains.js'),
  "saint-elias-mountains": () => import('./saint-elias-mountains.js'),
  "san-gabriel-mountains": () => import('./san-gabriel-mountains.js'),
  "san-jacinto-mountains": () => import('./san-jacinto-mountains.js'),
  "san-mateo-mountains": () => import('./san-mateo-mountains.js'),
  "san-rafael-mountains": () => import('./san-rafael-mountains.js'),
  "sangre-de-cristo-mountains": () => import('./sangre-de-cristo-mountains.js'),
  "sangre-de-cristo-range": () => import('./sangre-de-cristo-range.js'),
  "sawtooth": () => import('./sawtooth.js'),
  "selkirk-mountains": () => import('./selkirk-mountains.js'),
  "sierra-de-san-pedro-martir": () => import('./sierra-de-san-pedro-martir.js'),
  "sierra-estrella": () => import('./sierra-estrella.js'),
  "sierra-madre-del-sur": () => import('./sierra-madre-del-sur.js'),
  "sierra-madre-occidental": () => import('./sierra-madre-occidental.js'),
  "sierra-madre-oriental": () => import('./sierra-madre-oriental.js'),
  "sierra-mixteca": () => import('./sierra-mixteca.js'),
  "sierra-whitney": () => import('./sierra-whitney.js'),
  "skagit-range": () => import('./skagit-range.js'),
  "skeena-mountains": () => import('./skeena-mountains.js'),
  "strawberry-range": () => import('./strawberry-range.js'),
  "taconic-mountains": () => import('./taconic-mountains.js'),
  "tetons": () => import('./tetons.js'),
  "thudaka-range": () => import('./thudaka-range.js'),
  "toquima-range": () => import('./toquima-range.js'),
  "tordrillo-mountains": () => import('./tordrillo-mountains.js'),
  "tower-of-london-range": () => import('./tower-of-london-range.js'),
  "trans-mexican-volcanic-belt": () => import('./trans-mexican-volcanic-belt.js'),
  "vaca-mountains": () => import('./vaca-mountains.js'),
  "waddington-range": () => import('./waddington-range.js'),
  "wallowa-mountains": () => import('./wallowa-mountains.js'),
  "wasatch": () => import('./wasatch.js'),
  "white-mountains": () => import('./white-mountains.js'),
  "white-pine-range": () => import('./white-pine-range.js'),
  "wrangell-mountains": () => import('./wrangell-mountains.js'),
  "yukon-ranges": () => import('./yukon-ranges.js'),
};
