// The range basket at runtime: every range's scores are in ranges/index.js
// (generated by tools/build-ranges.mjs); each range's skyline profile is
// its own module, loaded only when a song is matched to it. That split is
// what lets the basket grow to hundreds of ranges without the page
// downloading all of them.
import { RANGES, LOADERS } from './ranges/index.js';
import { matchRange } from './RangeMatcher.js';
import { profilesFromJSON } from './TerrainProfile.js';

export { RANGES };

/** Pick the song's range from the whole basket. */
export function chooseRange(profile, seed) {
  return matchRange(RANGES, profile, seed);
}

/** Load a range's baked skyline and turn it into terrain profiles. Rejects
 *  on an unknown id or a profile TerrainProfile will not accept; callers
 *  fall back to the bundled Tetons. */
export async function loadRangeProfiles(id) {
  const load = LOADERS[id];
  if (!load) throw new Error(`no range '${id}' in the basket`);
  const mod = await load();
  return profilesFromJSON(mod.default);
}

/** Choose and load in one step. Resolves to {range, profiles} or null --
 *  never rejects, because a missing range must not stop a song. */
export async function prepareSongRange(profile, seed) {
  try {
    const match = chooseRange(profile, seed);
    if (!match) return null;
    return { range: match.range, profiles: await loadRangeProfiles(match.range.id) };
  } catch (err) {
    console.warn('[terrain] range unavailable; using the bundled Tetons', err);
    return null;
  }
}
