// The range basket at runtime: every range's scores are in ranges/index.js
// (generated by tools/build-ranges.mjs); each range's skyline profile is
// its own module, loaded only when a song is matched to it. That split is
// what lets the basket grow to hundreds of ranges without the page
// downloading all of them.
//
// A song gets three ranges, one per ridge: a high one at the back, a mid
// one in the middle and a low one in front (RangeMatcher.matchRidgeSet).
// Each range's module holds the skyline scanned for its far layer; that one
// skyline is what the song's ridge draws, whichever ridge it stands on.
import { RANGES, LOADERS } from './ranges/index.js';
import { RIDGE_BANDS, matchRidgeSet } from './RangeMatcher.js';
import { readRecentRanges } from './RangeHistory.js';
import { chooseSongBiomes, chooseBiomeRidges } from './BiomeSet.js';
import { profilesFromJSON } from './TerrainProfile.js';
import { chooseHorizonRange, MASSIF_SALT } from './HorizonRidge.js';

export { RANGES };

/** Pick the song's three ranges from the whole basket, passing over the
 *  ranges this player saw most recently: { far, mid, near } match results. */
export function chooseRanges(profile, seed, recent = readRecentRanges()) {
  return matchRidgeSet(RANGES, profile, seed, { recent });
}

/** Load a range's baked skyline and turn it into terrain profiles. Rejects
 *  on an unknown id or a profile TerrainProfile will not accept. */
export async function loadRangeProfiles(id) {
  const load = LOADERS[id];
  if (!load) throw new Error(`no range '${id}' in the basket`);
  const mod = await load();
  return profilesFromJSON(mod.default);
}

/**
 * Choose and load in one step. Resolves to
 *   { range, ranges: { far, mid, near }, profiles: { L2, L3, L4 } }
 * where `range` is the back (far) range, or null -- never rejects, because
 * a missing range must not stop a song. The back range is required; a
 * middle or front range that fails to load leaves that ridge to the
 * game's own invented hills.
 */
export async function prepareSongRange(profile, seed) {
  try {
    const set = chooseRanges(profile, seed);
    const loaded = await Promise.all(RIDGE_BANDS.map(async (b) => {
      const match = set[b.ridge];
      if (!match) return null;
      try {
        const layers = await loadRangeProfiles(match.range.id);
        const skyline = layers.L2;
        return skyline ? { ridge: b.ridge, layer: b.layer, range: match.range, skyline } : null;
      } catch (err) {
        if (b.ridge === 'far') throw err;
        console.warn(`[terrain] ${b.ridge} range unavailable; that ridge stays invented`, err);
        return null;
      }
    }));
    const far = loaded.find((x) => x?.ridge === 'far');
    if (!far) return null;
    const ranges = {};
    const profiles = {};
    for (const x of loaded) {
      if (!x) continue;
      ranges[x.ridge] = x.range;
      profiles[x.layer] = x.skyline;
    }
    return { range: far.range, ranges, profiles };
  } catch (err) {
    console.warn('[terrain] range unavailable; using the bundled Tetons', err);
    return null;
  }
}

/**
 * The song's biomes and the ranges standing in each (BiomeSet.js). Resolves
 * as soon as the home biome -- the one the song opens in -- has loaded, to
 *   { biomes, home, byBiome, whenAll, allLoaded, range, ranges, profiles, horizon, massif }
 * where `byBiome` maps a biome name to { ranges: { far, mid, near },
 * profiles: { L2, L3, L4 } } and fills in as the others load (`whenAll`
 * settles when they have), and `range`/`ranges`/`profiles` are the home
 * biome's. A biome whose back range fails to load is left out of byBiome,
 * and its sections draw the game's own hills. Resolves to null -- never
 * rejects -- when the home biome cannot load: the song falls back to the
 * bundled Tetons. `horizon` is { range, profile }, the famous skyline the
 * horizon EQ dances on (HorizonRidge.js), loaded alongside the home biome;
 * null when it failed, and the EQ keeps its own shape. `massif` is the same
 * for the spectrum massif behind it: another of those skylines, never the
 * horizon's.
 */
export async function prepareSongTerrain(profile, seed, recent = readRecentRanges()) {
  try {
    const biomes = chooseSongBiomes(profile, seed);
    if (!biomes.length) return null;
    const byBiome = new Map();
    const load = async (biome) => {
      const set = chooseBiomeRidges(biome, profile, seed, { recent });
      const loaded = await Promise.all(RIDGE_BANDS.map(async (b) => {
        const match = set[b.ridge];
        if (!match) return null;
        try {
          const layers = await loadRangeProfiles(match.range.id);
          return layers.L2 ? { ridge: b.ridge, layer: b.layer, range: match.range, skyline: layers.L2 } : null;
        } catch (err) {
          if (b.ridge === 'far') throw err;
          console.warn(`[terrain] ${biome} ${b.ridge} range unavailable; that ridge stays invented`, err);
          return null;
        }
      }));
      if (!loaded.some((x) => x?.ridge === 'far')) return null;
      const entry = { biome, ranges: {}, profiles: {} };
      for (const x of loaded) {
        if (!x) continue;
        entry.ranges[x.ridge] = x.range;
        entry.profiles[x.layer] = x.skyline;
      }
      byBiome.set(biome, entry);
      return entry;
    };
    const homeIds = Object.values(chooseBiomeRidges(biomes[0], profile, seed, { recent }))
      .map((m) => m?.range?.id).filter(Boolean);
    const loadSkyline = async (range, what) => {
      if (!range) return null;
      try {
        const layers = await loadRangeProfiles(range.id);
        return layers.L2 ? { range, profile: layers.L2 } : null;
      } catch (err) {
        console.warn(`[terrain] ${what} range unavailable; it keeps its own shape`, err);
        return null;
      }
    };
    const horizonRange = chooseHorizonRange(seed, { exclude: homeIds });
    const massifRange = chooseHorizonRange(seed, {
      exclude: [...homeIds, horizonRange?.id].filter(Boolean), salt: MASSIF_SALT,
    });
    const [home, horizon, massif] = await Promise.all([
      load(biomes[0]), loadSkyline(horizonRange, 'horizon'), loadSkyline(massifRange, 'massif'),
    ]);
    if (!home) return null;
    const whenAll = Promise.all(biomes.slice(1).map((b) => load(b).catch((err) => {
      console.warn(`[terrain] ${b} unavailable; its sections stay invented`, err);
      return null;
    })));
    const terrain = {
      biomes, home: biomes[0], byBiome, whenAll, allLoaded: false,
      range: home.ranges.far, ranges: home.ranges, profiles: home.profiles, horizon, massif,
    };
    whenAll.then(() => { terrain.allLoaded = true; });
    return terrain;
  } catch (err) {
    console.warn('[terrain] song biomes unavailable; using the bundled Tetons', err);
    return null;
  }
}
