// Build data/peaks.json: named summits (GeoNames feature codes PK, PKS, MT,
// MTS, VLC) around every range in data/ranges.json, for peak labels.
// Downloads the US/CA/MX GeoNames dumps into .tile-cache/geonames/.
//   node tools/build-peaks.mjs
import fs from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { expandBbox } from './compute-viewpoints.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cache = path.join(root, '.tile-cache', 'geonames');
const CODES = new Set(['PK', 'PKS', 'MT', 'MTS', 'VLC']);
const MARGIN_M = 60000;

async function dump(cc) {
  const txt = path.join(cache, `${cc}.txt`);
  try { await fs.access(txt); return txt; } catch { /* fetch */ }
  await fs.mkdir(cache, { recursive: true });
  const zip = path.join(cache, `${cc}.zip`);
  const res = await fetch(`https://download.geonames.org/export/dump/${cc}.zip`);
  if (!res.ok) throw new Error(`GeoNames ${cc}: HTTP ${res.status}`);
  await fs.writeFile(zip, Buffer.from(await res.arrayBuffer()));
  execFileSync('unzip', ['-o', zip, `${cc}.txt`, '-d', cache]);
  return txt;
}

const { ranges } = JSON.parse(await fs.readFile(path.join(root, 'data/ranges.json'), 'utf8'));
const boxes = ranges.map((r) => expandBbox(r.bbox, MARGIN_M));
const inside = (lon, lat) => boxes.some(([w, s, e, n]) => lon >= w && lon <= e && lat >= s && lat <= n);
const peaks = new Map();
for (const cc of ['US', 'CA', 'MX']) {
  const text = await fs.readFile(await dump(cc), 'utf8');
  for (const line of text.split('\n')) {
    const f = line.split('\t');
    if (f.length < 17 || f[6] !== 'T' || !CODES.has(f[7])) continue;
    const lat = Number(f[4]), lon = Number(f[5]);
    if (!inside(lon, lat)) continue;
    const elev = Number(f[15]) || Number(f[16]) || 0;
    if (elev < 300 || elev === -9999) continue;
    const name = f[1].trim();
    if (!name) continue;
    const key = `${name}|${lon.toFixed(2)}|${lat.toFixed(2)}`;
    if (!peaks.has(key)) peaks.set(key, [name, Math.round(lon * 1e5) / 1e5, Math.round(lat * 1e5) / 1e5, Math.round(elev)]);
  }
  console.log(`${cc}: ${peaks.size} peaks so far`);
}
const list = [...peaks.values()].sort((a, b) => b[3] - a[3]);
await fs.writeFile(path.join(root, 'data/peaks.json'), JSON.stringify({
  about: 'Named summits near Ridgeview ranges, from GeoNames (geonames.org, CC BY 4.0), feature codes PK/PKS/MT/MTS/VLC. Rows: [name, lon, lat, elevation m (GeoNames elevation, else its DEM value)]. Generated by tools/build-peaks.mjs.',
  peaks: list,
}) + '\n');
console.log(`wrote ${list.length} peaks`);
